### ISSUE TITLE
RemovedInDjango110Warning render() must be called with a dict, not a Context

### ISSUE THREAD

**Issue by nordbit** [edoburu/django-fluent-comments#71]
```
fluent_comments_tags.py:120: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return self.nodelist.render(context)
```

**Comment by PetrDlouhy** [comment]
This is fixed in PR #73

**Comment by nordbit** [comment]
So far all errors disappered. 
Tested with django==1.9.1 and python==3.5.1
Thank You Peter for your contribution.

**Comment by vdboor** [comment]
Thanks @PetrDlouhy! I've also merged your pull request now.

**Comment by nq-ebaratte** [comment]
@vdboor Can we reopen this ? I still see this warning with python 2.7.8, Django 1.9.5, fluent-comments 1.2

    fluent_comments/templatetags/fluent_comments_tags.py:124: RemovedInDjango110Warning: render() must be called with a dict, not a Context.

**Comment by vdboor** [comment]
@nq-ebaratte : I think you have a stale version somewhere, because the line numbers don't match. try to uninstall django-fluent-comments and remove any remaining files before you reinstall it. I've also released 1.2.1 with a minor bugfix.

**Comment by nq-ebaratte** [comment]
I carefully checked the version I use; it seems to be up to date. Note that replacing fluent_comment_tags.py:124

    return self.nodelist.render(context)

by 

    return self.nodelist.render(context.flatten())

clears the warning.
